# Python versions for matrix
language: python
python:
  - "2.7"
  - "2.6"
  - "3.2"
  - "3.3"

# Django versions for matrix
env:
  - DJANGO_VERSION=1.4.12
  - DJANGO_VERSION=1.5.7
  - DJANGO_VERSION=1.6.4

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors --quiet
  - pip install coveralls

# Command to run tests, e.g. python setup.py test
script:
  - coverage run --source=bootstrap3 manage.py test

# Support Python3 only with Django 1.6
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.4.12
    - python: "3.3"
      env: DJANGO_VERSION=1.4.12
    - python: "3.2"
      env: DJANGO_VERSION=1.5.7
    - python: "3.3"
      env: DJANGO_VERSION=1.5.7

# Report to coveralls
after_success:
  - coveralls
